apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: localstack
  namespace: localstack
spec:
  interval: 30m
  chart:
    spec:
      chart: localstack
      version: "0.6.*"
      sourceRef:
        kind: HelmRepository
        name: localstack
        namespace: localstack
      interval: 12h
  values:
    startServices: "s3,sqs,sns,dynamodb,lambda,iam,sts,cloudwatch,logs,ssm,secretsmanager"
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    enableStartupScripts: true
    startupScriptContent: |
      #!/bin/bash
      awslocal secretsmanager create-secret \
        --name crossplane-aws-credentials \
        --region us-east-1 \
        --secret-string "[default]
      aws_access_key_id = test
      aws_secret_access_key = test"
