apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - localstack.yaml
  - external-secrets.yaml
  - crossplane-base.yaml
  - crossplane-config.yaml
  - crossplane-provider-aws.yaml
